FROM ghcr.io/gbraad-devenv/almalinux/base:9

USER gbraad

RUN git clone https://github.com/gbraad/dotfiles ~/.dotfiles \
    && rm -f ~/.zshrc \
    && ~/.dotfiles/install.sh

ENTRYPOINT [ "/bin/zsh" ]